/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import com.sun.corba.se.impl.encoding.CodeSetConversion;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import outils.ButtonEditor;
import outils.ConnexionBdd;
import outils.TableModel;

/**
 *
 * @author jonathan
 */
public class MainWindow extends javax.swing.JFrame {


    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        try {
            initComponents();
            ConnexionBdd con = new ConnexionBdd();
            String sql ="select * from circuit";
            String[] enteteCircuit = { "Id", "Descriptif", "VilleDepart", "VilleDarrive", "PaysArrive","DateDepart","NbPlaceDisponible","Duree","Prix"};
                        
            TableModel model = new TableModel(con,sql,enteteCircuit);
            jTable2.setModel(model); 
            System.out.print("nb ligne :"+jTable2.getRowCount());
            System.out.println(" nb col :"+jTable2.getColumnCount()+"__");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();
        jBtnSuppr = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setCellSelectionEnabled(true);
        jTable2.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                jTable2AncestorResized(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jScrollPane2.setBounds(10, 10, 660, 270);
        jDesktopPane1.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(10, 300, 660, 60);
        jDesktopPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Circuit", "Etape", "Lieux à visiter", "Client", "Réserver" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Choisissez une table :");

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        jBtnSuppr.setText("Supprimer");
        jBtnSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSupprActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnModifier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnSuppr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnSuppr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        try {
            System.out.println("ActionListener : action sur " + jComboBox1.getSelectedItem());
            String value = (String) jComboBox1.getSelectedItem();
            ConnexionBdd con = new ConnexionBdd();
            switch (value)
            {
                case "Circuit" :             
                    //ConnexionBdd con = new ConnexionBdd();
                    String sql ="select * from circuit";
                    String[] enteteCircuit = { "Id", "Descriptif", "VilleDepart", "VilleDarrive", "PaysArrive","DateDepart","NbPlaceDisponible","Duree","Prix"};
                    
                    TableModel model = new TableModel(con,sql,enteteCircuit);
                    jTable2.setModel(model); 
                    //JComboBox myCombo = new JComboBox();
                   // jTable2.getColumn("Prix").setCellEditor(new DefaultCellEditor(myCombo));
                   
                    ; break;
                case "Réserver" : 
                    String sqlTabReserv ="select * from reserver";
                    String[] enteteReserver = { "Id réservation", "nombre de places", "date de réservation", "id circuit", "id client" };
                    
                    TableModel model2 = new TableModel(con,sqlTabReserv,enteteReserver);
                    jTable2.setModel(model2); 
                    
                    ; break;
                    
                 case "Etape" : 
                    String sqlTabEtape ="select * from etape";
                    String[] enteteEtape = { "Ordre", "Pays", "date Etape", "Durée", "id client","Nom lieu","Ville" };
                    
                    TableModel model3 = new TableModel(con,sqlTabEtape,enteteEtape);
                    jTable2.setModel(model3); 
                    
                    
                    ; break;
                     
                 case "Client" : 
                    String sqlTabClient ="select * from client";
                    String[] enteteClient = { "Id réservation", "nombre de places", "date de réservation", "id circuit", "id client" };
                    
                    TableModel model4 = new TableModel(con,sqlTabClient,enteteClient);
                    jTable2.setModel(model4); 
                    
                    ; break;  
                     
                 case "Lieux à visiter" : 
                    String sqlTabLieux ="select * from lieuxavisiter";
                    String[] enteteLieux = { "Id réservation", "nombre de places", "date de réservation", "id circuit", "id client" };
                    
                    TableModel model5 = new TableModel(con,sqlTabLieux,enteteLieux);
                    jTable2.setModel(model5); 
                    
                    ; break;      
                           
                    
                    
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTable2AncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTable2AncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2AncestorResized
    
    public Object[] getRow(int IndexRow){
        Object[] tabObj = new Object[jTable2.getColumnCount()];
            for(int i = 0;i< jTable2.getColumnCount();i++){
                //JOptionPane.showMessageDialog(null,"getvalueat("+IndexRow+","+i+")="+jTable2.getModel().getValueAt(IndexRow,i));
                tabObj[i] = jTable2.getModel().getValueAt(IndexRow,i);
                //System.out.print("getvalueat("+IndexRow+","+i+")");
            }
            String resTab = "[";
            //System.out.print("contenu du tabobj = [");
            for(int i = 0;i< jTable2.getColumnCount();i++){
                resTab+=tabObj[i]+",";
                //System.out.print(tabObj[i]+",");
            }
            resTab+="]";
            System.out.print(resTab);
            JOptionPane.showMessageDialog(null,resTab);
        return tabObj; 
    }
    
    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
JOptionPane.showMessageDialog(null,"cliquez sur la ligne à modifier");
  jTable2.addMouseListener(new MouseAdapter() {
  @Override
  public void mouseClicked(MouseEvent e) {
    Point p = e.getPoint();
    int row = jTable2.rowAtPoint(p);
    int col = jTable2.columnAtPoint(p);
    //getRow(row);
    getRow(row);
    JOptionPane.showMessageDialog(null,"row: "+row+"col :"+col);
   
    jTable2.setValueAt(JOptionPane.showInputDialog(null,"Enter Cell Value:"),jTable2.getSelectedRow(),jTable2.getSelectedColumn());
    System.out.print("iscelleditable:"+jTable2.isCellEditable(row, col));
    if (jTable2.isCellEditable(row, col)) {
        boolean editCellAt = jTable2.editCellAt(row, col);
      jTable2.getEditorComponent().requestFocus();

    }
   
  }
});        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifierActionPerformed

    private void jBtnSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSupprActionPerformed
        //TableModel model = (outils.TableModel) jTable2.getModel().removeTableModelListener(jTable1);

    }//GEN-LAST:event_jBtnSupprActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton jBtnSuppr;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    private void JButton() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
